#ifndef GG_PROFILE_H
#define GG_PROFILE_H
#define GG_PROFILE_MAGIC "DCPRO_GHOSTGUARD_NATIVE_PROFILE_V5"
enum gg_profile_state {
    GG_PROFILE_CALIBRATION=0,
    GG_PROFILE_READY=1,
    GG_PROFILE_PENDING_APPROVAL=2,
    GG_PROFILE_APPROVED=3,
    GG_PROFILE_PROBATION=4,
    GG_PROFILE_PROTECT=5
};
#endif
